"""
backend.core.events - Event system for graph mutations

This package provides event generation, filtering, and webhook delivery
for graph mutation events (node/edge create, update, delete).

Main components:
- Event: Data model for mutation events
- EventContext: Context for tracking event origin and correlation
- EventDispatcher: Filters and routes events to subscriptions
- DeliveryWorker: Async webhook delivery with retries

Usage:
    from backend.core.events import (
        Event, EventContext, EventDispatcher, DeliveryWorker
    )

    # Create context for tracking
    ctx = EventContext(event_origin="web-ui", event_session_id="abc123")

    # Events are automatically generated by GraphStorage when mutations occur
"""

from .models import (
    Event,
    EventType,
    EntityKind,
    EventContext,
    EventOrigin,
    DeliveryResult,
    DeliveryStatus,
    SubscriptionFilters,
    SubscriptionDelivery,
)

from .dispatcher import EventDispatcher

from .delivery import DeliveryWorker

__all__ = [
    # Models
    "Event",
    "EventType",
    "EntityKind",
    "EventContext",
    "EventOrigin",
    "DeliveryResult",
    "DeliveryStatus",
    "SubscriptionFilters",
    "SubscriptionDelivery",
    # Dispatcher
    "EventDispatcher",
    # Delivery
    "DeliveryWorker",
]
